version: 2
jobs:
  test_graphql:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-graphql-dependencies-{{ checksum "package-lock.json" }}
            - v1-graphql-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-graphql-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Run tests
          command: npm test
workflows:
  version: 2
  ultimate_pipeline:
    jobs:
      - test_graphql